name: Release geosite.dat

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout domain-list-community
        uses: actions/checkout@v7
        with:
          repository: v2fly/domain-list-community
          ref: master
          path: source

      - name: Checkout geoip
        uses: actions/checkout@v7
        with:
          repository: v2fly/geoip
          ref: master
          path: geoip-source

      - name: Override geoip source
        run: |
          cp -rpf geoip/* geoip-source/

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: source/go.mod
          cache-dependency-path: source/go.sum

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: geoip-source/go.mod
          cache-dependency-path: geoip-source/go.sum

      - name: Build
        run: |
          chmod +x geosite/build.sh
          ./geosite/build.sh source

      - name: Build geoip
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          chmod +x geoip-source/build.sh
          ./geoip-source/build.sh geoip-source

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          gh release create "$TAG" \
            --latest \
            --title "$TAG" \
            ./geosite.dat \
            ./geosite.dat.sha256 \
            ./geoip.dat \
            ./geoip.dat.sha256

      - name: Cleanup old releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list \
            --limit 100 \
            --json tagName,isLatest \
            --jq '[.[] | select(.isLatest == false) | .tagName] | .[12:] | .[]' |
          while read -r tag; do
            gh release delete "$tag" --yes
          done
